### ISSUE TITLE
样例巴塞尔问题程序计算的同态计算结果与明文计算结果不一致

### ISSUE THREAD

**Issue by Gray-byte** [primihub/hehub#2]
按照配置要求完成了环境部署后

运行了build/examples/ckks_example可执行程序

设置循环50次

代码如下

![image](https://user-images.githubusercontent.com/81550687/197915803-211949fc-f2c4-454c-8dd1-8b11e6cc0439.png)

运行结果如下

可以看到结果的密文计算和明文计算的结果并不相等

![image](https://user-images.githubusercontent.com/81550687/197915874-4c3b6040-7ca9-4dec-ba0a-1b5aa8b23e58.png)

为了便于查看中间结果

打印for循环过程中的各个同态乘法运算结果

加入如下代码

![image](https://user-images.githubusercontent.com/81550687/197915590-9a410597-0bdb-4878-807c-ad43ecd8eeb4.png)

结果如下

![image](https://user-images.githubusercontent.com/81550687/197915472-e391fa1f-c1cd-475a-b223-177a9551a8f8.png)

可以看到，对于特定的一部分i，运算结果存在问题

即便是同一个i=2，运算执行多次，结果也会不一样

测试代码如下

![image](https://user-images.githubusercontent.com/81550687/197914476-fb5394f8-0a36-456c-bd1a-811d09c0c0db.png)

结果如下

![image](https://user-images.githubusercontent.com/81550687/197914744-35278435-1a48-47a0-bdba-c6f84ef86596.png)

同样的计算，第二次的计算结果和其他三次差异很大

-----------------------------------

不确定是我的代码使用存在问题，还是库函数中部分代码存在问题

**Comment by ppppbamzy** [comment]
example 目前还在 fix 中，预计今天调试出来

**Comment by Gray-byte** [comment]
> example 目前还在 fix 中，预计今天调试出来

好的好的

**Comment by ppppbamzy** [comment]
现在应该可以了，找到了一个bug: 945ef4ad79ba7ddccfd4e805ea70867a590951c2
可以帮忙多测试几次
