### ISSUE TITLE
编译错误 basics.cpp

### ISSUE THREAD

**Issue by wangshankun** [primihub/hehub#3]
![image](https://user-images.githubusercontent.com/3970271/198050037-b85a8817-33c9-4258-9f11-a227b891956d.png)

`/home/wsk/code/hehub/src/fhe/ckks/basics.cpp: In function ‘std::vector<std::complex<double> > hehub::ckks::simd_decode_cc(const hehub::ckks::CkksPt&, size_t)’:
/home/wsk/code/hehub/src/fhe/ckks/basics.cpp:300:76: error: class template argument deduction failed:
     vector rest_moduli(pt.modulus_vec().begin() + 1, pt.modulus_vec().end());
                                                                            ^
/home/wsk/code/hehub/src/fhe/ckks/basics.cpp:300:76: error: no matching function for call to ‘vector(__gnu_cxx::__normal_iterator<const long unsigned int*, std::vector<long unsigned int> >, std::vector<long unsigned int>::const_iterator)’
In file included from /usr/include/c++/7/vector:64:0,
                 from /home/wsk/code/hehub/src/fhe/commo`

**Comment by ppppbamzy** [comment]
用的是什么编译器？我测试一下

**Comment by ppppbamzy** [comment]
我的环境里有gcc-8和gcc-7，默认是gcc-8。刚才测试了一遍gcc-8可以编译，gcc-7不行。

之前一直以为默认是gcc-7

**Comment by wangshankun** [comment]
> 

是的，我是gcc-7

**Comment by ppppbamzy** [comment]
现在把README里的说明修正了，改成要求gcc>=8.0
