### ISSUE TITLE
install 失败

### ISSUE THREAD

**Issue by DumbDonaldDuck** [primihub/hehub#6]
![hehub-1](https://user-images.githubusercontent.com/93831383/199003516-5fdcdd19-8212-4dad-b522-81c017e46149.png)
根据 Readme ，我在 install 的时候只有这个输出，cmakelist中的后续部分都没有执行。
在测试 test.cpp 的时候，也会出现“ckks/ckks.h"找不到的错误。

**Comment by ppppbamzy** [comment]
刚刚更新了代码 fa75efe58e6b0d140ecde6a7519e45ff4ab820a5 ，现在头文件会安装到“<系统include路径>/fhe/”

**Comment by ppppbamzy** [comment]
刚才更新了代码，现在应该可以install了。引用格式改成了#include "fhe/ckks/ckks.h"

**Comment by DumbDonaldDuck** [comment]
好的我再试一试，谢谢～Get Outlook for Android
